### PR TITLE
[Reviewer: Steve] Replace values on an individual basis

### PR DESCRIPTION
**Pull request by Tom-Rees**
Testing required.

### CODE REVIEW

**Comment by Tom-Rees** [comment]
Tested on l3-cc4-hstead2. Fixed initial issue, and no evidence that it broke anything else.

Steve, could you please review before I send to PC?

Cheers,
Tom

**Comment by steelyvoid** [comment]
Did you check that, if XDM_URL is defined by default to be something "interesting" from an escape PoV (in other words, containing forward slashes) that it still has the right number of forward slashes afterwards?  Probably worth trying if not

**Comment by Tom-Rees** [comment]
[homestead]clearwater@l3-cc4-hstead2:~$ sudo cat /usr/share/clearwater/clearwater-prov-tools/local_settings.py | grep 'XDM_URL'
XDM_URL = MUS/ space / \..\/\T_BE_CONFIGURED

>>> print settings.XDM_URL
MUS/ space / \..\/\T_BE_CONFIGURED.

The escaping would previously break on a space.


The only thing I'm worried about is that we now always use the values in usr/share/clearwater/clearwater-prov-tools/local_settings.py whereas previously we would use the defaults in /usr/share/clearwater/clearwater-prov-tools/ ... /settings.py.

E.g. XDM_URL now defaults to 'MUST_BE_CONFIGURED' instead of 'homer.cw-ngv.com:7888'. Which I think is an improvement as it's clear that this is a configuration issue, not DNS/Naming related.

**Comment by steelyvoid** [comment]
I agree.  It would seem to make more sense to change it to something like "XDM_NOT_CONFIGURED", but I guess its their call

**Pull request merged**
